{{- if .Values.bigbangStatus.enabled -}}

{{- $custom := dict "" "" }}
{{- $_ := set $custom "serviceAccountName" (include "bigbang-status.service-account-name" .) }}
{{- $_ := set $custom "labels" (include "bigbang-status.labels" .) }}
{{- $_ := set $custom "annotations" (include "bigbang-status.service-account-annotations" .) }}
{{- $_ := set $custom "fullname" (include "bigbang-status.fullname" .) }}
{{- $_ := set $custom "schedule" .Values.bigbangStatus.schedule }}
{{- $_ := set $custom "command" (include "bigbang-status.command" .) }}
{{- $_ := set $custom "args" (include "bigbang-status.args" .) }}

{{- $args := dict "scope" . "custom" $custom }}

{{- include "bbctl.common.cron-job" $args | nindent 0 }}
{{- end }}
