{{- if .Values.bigbangTemplate.enabled }}

{{- $custom := dict "" "" }}
{{ $_ := set $custom "fullname" (include "bigbang-template.fullname" .) }}
{{ $_ := set $custom "labels" (include "bigbang-template.labels" .) }}
{{ $_ := set $custom "config" (include "bigbang-template.config" . | print) }}

{{- $args := dict "scope" . "custom" $custom }}

{{- include "bbctl.common.config-maps" $args | nindent 0 }}
{{- end }}
