{{- $createSecret := false -}}
{{- $secretData := dict -}}

{{- if .Values.credentialsFile.credentials -}}
  {{- $createSecret = true -}}
  {{- $_ := set $secretData "credentials.yaml" (toYaml .Values.credentialsFile | b64enc) -}}
{{- end -}}

{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bbctl.fullname" . }}-credentials
  labels:
    {{- include "bbctl.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
