{{- $createSecret := false -}}
{{- $secretData := dict -}}

{{- if .Values.credentialsFile.credentials -}}
  {{- $createSecret = true -}}
  {{- $_ := set $secretData "credentials.yaml" (toYaml .Values.credentialsFile | b64enc) -}}
{{- else if .Values.registryCredentials.password -}}
  {{- $createSecret = true -}}
  {{- $creds := printf "credentials:\n- uri: %s\n  username: %s\n  password: %s" .Values.registryCredentials.registry .Values.registryCredentials.username .Values.registryCredentials.password -}}
  {{- $_ := set $secretData "credentials.yaml" ($creds | b64enc) -}}
{{- end -}}

{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bbctl.fullname" . }}-credentials
  labels:
    {{- include "bbctl.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
