// Code generated by mockery v2.43.2. DO NOT EDIT.

package static

import (
	mock "github.com/stretchr/testify/mock"
	static "repo1.dso.mil/big-bang/product/packages/bbctl/static"
)

// MockConstantsClient is an autogenerated mock type for the ConstantsClient type
type MockConstantsClient struct {
	mock.Mock
}

type MockConstantsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConstantsClient) EXPECT() *MockConstantsClient_Expecter {
	return &MockConstantsClient_Expecter{mock: &_m.Mock}
}

// GetConstants provides a mock function with given fields:
func (_m *MockConstantsClient) GetConstants() (static.Constants, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConstants")
	}

	var r0 static.Constants
	var r1 error
	if rf, ok := ret.Get(0).(func() (static.Constants, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() static.Constants); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(static.Constants)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConstantsClient_GetConstants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConstants'
type MockConstantsClient_GetConstants_Call struct {
	*mock.Call
}

// GetConstants is a helper method to define mock.On call
func (_e *MockConstantsClient_Expecter) GetConstants() *MockConstantsClient_GetConstants_Call {
	return &MockConstantsClient_GetConstants_Call{Call: _e.mock.On("GetConstants")}
}

func (_c *MockConstantsClient_GetConstants_Call) Run(run func()) *MockConstantsClient_GetConstants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConstantsClient_GetConstants_Call) Return(_a0 static.Constants, _a1 error) *MockConstantsClient_GetConstants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConstantsClient_GetConstants_Call) RunAndReturn(run func() (static.Constants, error)) *MockConstantsClient_GetConstants_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConstantsClient creates a new instance of MockConstantsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConstantsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConstantsClient {
	mock := &MockConstantsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
