{
 "title": "all-logs-dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Versions Logs",
   "type": "table",
   "description": "All logs pulled from all the existing cluster bbctl cronjobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"bbctl-bigbang-updater\", container=\"bbctl\"}"
    }
   ]
  },
  {
   "title": "Policy Logs",
   "type": "table",
   "description": "bbctl policy --kyverno",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"bbctl-bigbang-policy\", container=\"bbctl\"}"
    }
   ]
  },
  {
   "title": "Preflight Check Logs",
   "type": "table",
   "description": "bbctl preflight-check",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"bbctl-bigbang-preflight\", container=\"bbctl\"}"
    }
   ]
  },
  {
   "title": "Status Logs",
   "type": "table",
   "description": "bbctl status",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"bbctl-bigbang-status\", container=\"bbctl\"}"
    }
   ]
  },
  {
   "title": "Violations Logs",
   "type": "table",
   "description": "bbctl violations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"bbctl-bigbang-violations\", container=\"bbctl\"}"
    }
   ]
  }
 ]
}