{{- if .Values.bigbangPolicy.enabled }}

{{- $custom := dict "" "" }}
{{ $_ := set $custom "fullname" (include "bigbang-policy.fullname" .) }}
{{ $_ := set $custom "labels" (include "bigbang-policy.labels" .) }}
{{ $_ := set $custom "config" (include "bigbang-policy.config" . | print) }}

{{- $args := dict "scope" . "custom" $custom }}

{{- include "bbctl.common.config-maps" $args | nindent 0 }}
{{- end }}
